<a href="https://colab.research.google.com/github/saloni1901/Pandas-Numpy-Matplot-Seaborn-basic/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#how to save file in numpy
t=np.arange(12).reshape(4,3)
np.savetxt('test.txt',t)
#y=np.loadtxt('test.txt')

In [ ]:
i=np.array([1,2,34,4],dtype='float')
i.ndim

1

In [ ]:
np.sqrt(i)

array([1.        , 1.41421356, 5.83095189, 2.        ])

In [ ]:
i.itemsize

8

In [ ]:
i.dtype

dtype('float64')

In [ ]:
ii=np.array([[1,2],[2,4]])
ii.ndim

2

In [ ]:
ii.itemsize

8

In [ ]:
ii.size

4

In [ ]:
ii.shape

(2, 2)

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
t=np.ones((3,4))
t

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
t.reshape(4,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
t.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
ii.min()

1

In [ ]:
ii.max()

4

In [ ]:
t.sum()

12.0

In [ ]:
t.sum(axis=0)

array([3., 3., 3., 3.])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1,5,2)

array([1, 3])

In [ ]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [ ]:
#we can do also matrix a*b,a.dot(b),a+b,a-b,a/b

In [ ]:
p=np.array([[1,2],[4,5],[7,9]])
p

array([[1, 2],
       [4, 5],
       [7, 9]])

In [ ]:
p[1,1]

5

In [ ]:
for a in p:
  print(a)

[1 2]
[4 5]
[7 9]


In [ ]:
for t in p.flat:
  print(t)

1
2
4
5
7
9


In [ ]:
np.vstack((ii,p))#for horizontla hstack

array([[1, 2],
       [2, 4],
       [1, 2],
       [4, 5],
       [7, 9]])

In [ ]:
y=np.arange(0,90).reshape(10,9)
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [ ]:
np.hsplit(y,3)

[array([[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20],
        [27, 28, 29],
        [36, 37, 38],
        [45, 46, 47],
        [54, 55, 56],
        [63, 64, 65],
        [72, 73, 74],
        [81, 82, 83]]), array([[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23],
        [30, 31, 32],
        [39, 40, 41],
        [48, 49, 50],
        [57, 58, 59],
        [66, 67, 68],
        [75, 76, 77],
        [84, 85, 86]]), array([[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26],
        [33, 34, 35],
        [42, 43, 44],
        [51, 52, 53],
        [60, 61, 62],
        [69, 70, 71],
        [78, 79, 80],
        [87, 88, 89]])]

In [ ]:
o=np.arange(12).reshape(3,4)
o

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b=o>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
o[o>4]

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
o[b]=-1
o

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])